services:
  valheim:
    image: ghcr.io/community-valheim-tools/valheim-server:latest
    container_name: valheim-server
    cap_add:
      - SYS_NICE
    env_file:
      - valheim.env
    volumes:
      - ./valheim-data/config:/config
      - ./valheim-data/data:/opt/valheim
    ports:
      - "2456-2458:2456-2458/udp"
    restart: unless-stopped
    stop_grace_period: 2m
