server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = /status.json {
    proxy_pass http://valheim:80/status.json;
    proxy_no_cache 1;
    add_header Cache-Control "no-store" always;
  }

  location / {
    try_files $uri $uri/ =404;
  }
}
